# 使用该命令安装conda create -f conda_environment.yaml
# 使用该命令激活conda activate fruit_flavor_analysis
name: fruit_flavor_analysis
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  # 原始conda源作为后备
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - scikit-learn
    - pandas
    - matplotlib
    - seaborn
    - openpyxl
    - PyWGCNA
    - xgboost
    - statsmodels